version: 1.0.{build}
os: Visual Studio 2015
install:
- ps: >-
    ./InstallDnx.ps1
build:
  verbosity: minimal
after_build:
- dnu pack --framework dotnet --configuration release src/FreeMobile.FreeMobileSmsApi
artifacts:
- path: src/FreeMobile.FreeMobileSmsApi/bin/release/*.nupkg
  name: FreeMobile.FreeMobileSmsApi